language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t thobelacs/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true thobelacs/docker-react npm run test